[package]
name = "tundra"
version = "0.1.0"
authors = ["Guy Watson <guy.w@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.7.0"
cairo-rs = { version = "^0", features = ["png"] }
gio = "^0"