[package]
name = "tundra_r"
version = "0.1.0"
authors = ["Guy Watson <guy.w@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod = "0.61.1"
